name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run test
        env:
          GIST_TOKEN: ${{ secrets.GIST_SECRET }}
      - run: npm run build
      - run: sed -i '0,/index.js/s//dist\/index.js/' action.yml package.json
      - run: rm -rf test/data
      - uses: ./
        with:
          gist-id: ${{ secrets.GIST_ID }}
          token: ${{ secrets.GIST_SECRET }}
